apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-front
  labels:
    app: my-app-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-front
  template:
    metadata:
      labels:
        app: my-app-front
    spec:
      containers:
      - name: udagram-frontend
        image: nanotorre/udagram-frontend
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080